/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rurki;

public class MainClass {

    public static void main(String[] args) {
        Matrix A = new Matrix(1, 1);

        A.putVal(0, 0, 2);

        System.out.println(A);
        System.out.println(A.inverse());

        
    }
}
