/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rurki;

public class MainClass {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MainClass().getGreeting());
    }
}
